# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=40),
        ),
    ]
